version: '3'
services:
  develop:
    build: .
    command: yarn run gridsome develop --host 0.0.0.0
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - nodemodules:/usr/src/app/node_modules
    ports:
      - "8080:8080"
volumes:
  nodemodules: